# Site settings
title: Pepitas Repostería Creativa
email: andrea1082@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Producción de cupcakes, respostería creativa y artística en Medellín, Colombia
baseurl: /sitio_web # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:
whatsapp_username: +57 3215455497  

# Build settings
markdown: kramdown
permalink: pretty
